### ISSUE TITLE
added task to pre-commit and after success won't fire git commit.

### ISSUE THREAD

**Issue by premiumwd** [bahmutov/pre-git#108]
Hi,

Anyway to accomplish this. I have pre-git task, need to turn off jasmine if passed all tests, any clue?
```
"config": {
    "pre-git": {
      "enabled": true,
      "msg-pattern": "^(US|DE)\\d+ - .+",
      "commit-msg": "validate-commit-msg",
      "pre-commit": [
        "npm run sass-lint && npm run ts-lint",
        "npm test --single-run"
      ],
      "pre-push": [
        "npm e2e"
      ],
      "post-commit": "git status",
      "post-checkout": [],
      "post-merge": []
    }
  }
```

### Expected behaviour
--single-run in command line, run once.
### Actual behaviour
doesn't end process
### Environment Details

- Karma version (output of `karma --version`):
- Relevant part of your `karma.config.js` file

### Steps to reproduce the behaviour

1. karma start --single-run --watch=false

**karma.conf.js**
```
// Karma configuration file, see link for more information
// https://karma-runner.github.io/0.13/config/configuration-file.html

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular/cli'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'), // add the phantom launcher
      require('@angular/cli/plugins/karma'),
      require('karma-mocha-reporter')
    ], 
    mochaReporter: {
      colors: {
        success: 'green',
        info: 'grey',
        warning: 'yellow',
        error: 'red'
      },
      output: 'autowatch',
      showDiff: true
    },
    client:{
      clearContext: false, // leave Jasmine Spec Runner output visible in browser
      args: ['--grep', config.grep]
    }, 
    files: [
      { pattern: './src/test.ts', watched: false },
      { pattern: './node_modules/intl/locale-data/jsonp/en-US.js', watched: false }
    ],
    preprocessors: {
      './src/test.ts': ['@angular/cli']
    },  
    mime: {
      'text/x-typescript': ['ts','tsx']
    },      
    angularCli: {
      environment: 'dev'
    },    
    reporters: ['mocha'],    
    port: 9876,
    colors: true,   
    logLevel: config.LOG_INFO,
    autoWatch: true, 
    browsers: ['ChromeHeadless'],    
    singleRun: false
  });
};
```

**Comment by bahmutov** [comment]
weird, can you run the precommit hook by itself? Like `DEBUG=pre-git ./.git/hook/precommit`?

**Comment by premiumwd** [comment]
It runs fine but with karma added to test, it just doesn't do anything. I am using mocha btw.

```
H:\d>git commit -m "first pregit commit"
running bin/pre-commit.js script
executing task "DEBUG=pre-git ./.git/hook/precommit"
'DEBUG' is not recognized as an internal or external command,
operable program or batch file.

pre-commit You've failed to pass all the hooks.
pre-commit
pre-commit An Error was thrown from command
DEBUG=pre-git ./.git/hook/precommit
Error: DEBUG=pre-git ./.git/hook/precommit closed with code 1
pre-commit
pre-commit    at ChildProcess.onTaskFinished (H:\d\node_modules\pre-git\src\pre-git.js:247:19)
pre-commit    at emitTwo (events.js:130:20)
pre-commit    at ChildProcess.emit (events.js:213:7)
pre-commit    at maybeClose (internal/child_process.js:897:16)
pre-commit    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
pre-commit
pre-commit You can skip the git hook by running with -n (--no-verify)
pre-commit
pre-commit But this is not advised as your tests are obviously failing.
```
