### ISSUE TITLE
Remove hardcoded path to commitizen plugin

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/pre-git#40]
```js
pkg.czConfig = {
    path: 'node_modules/pre-git/node_modules/cz-conventional-changelog'
};
```

**Comment by bahmutov** [comment]
Currently npm@3 breaks because the path is not there
```
$ npm run commit

> javascript-journey@1.0.0 commit /Users/gleb/git/javascript-journey
> commit-wizard


********
WARNING: This repository's package.json is using czConfig. czConfig will be deprecated in Commitizen 3. 
Please use this instead:
{
  "config": {
    "commitizen": {
      "path": "./path/to/adapter"
    }
  }
}
For more information, see: http://commitizen.github.io/cz-cli/
********

/Users/gleb/git/javascript-journey/node_modules/commitizen/dist/commitizen/adapter.js:162
    throw err;
          ^
Error: ENOENT, no such file or directory '/Users/gleb/git/javascript-journey/node_modules/pre-git/node_modules/cz-conventional-changelog'
    at Error (native)
    at Object.fs.lstatSync (fs.js:792:18)
    at resolveAdapterPath (/Users/gleb/git/javascript-journey/node_modules/commitizen/dist/commitizen/adapter.js:151:25)
    at getPrompter (/Users/gleb/git/javascript-journey/node_modules/commitizen/dist/commitizen/adapter.js:128:29)
    at gitCz (/Users/gleb/git/javascript-journey/node_modules/commitizen/dist/cli/strategies/git-cz.js:76:18)
    at Object.bootstrap (/Users/gleb/git/javascript-journey/node_modules/commitizen/dist/cli/git-cz.js:29:27)
    at Object.<anonymous> (/Users/gleb/git/javascript-journey/node_modules/commitizen/bin/git-cz.js:2:34)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/Users/gleb/.nvm/versions/node/v0.12.7/bin/npm" "run" "commit"
npm ERR! node v0.12.7
npm ERR! npm  v3.3.9
```
the installed paths are flat
```
ls node_modules/
pre-git/
commitizen/
cz-conventional-changelog/
```

**Comment by bahmutov** [comment]
Similarly, cannot find "validate-commit-msg"
```
pre-commit Nothing the hook needs to do. Bailing out.

commit-msg in /Users/gleb/git/javascript-journey
using built-in validator validate-commit-msg
module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/gleb/git/javascript-journey/node_modules/pre-git/node_modules/validate-commit-msg'
```

**Comment by bahmutov** [comment]
Finally, pre-git@1.2.11 resolves it
